### ISSUE TITLE
retour d'information

### ISSUE THREAD

**Issue by nlienard** [Aymkdn/assistant-launch#1]
Bonjour,
J'ai la GH depuis 2jours, et c'est vraiment sympa d'avoir trouvé ton git pour controller la télé.
Pour launch, j'ai fait un test et ca marche très bien, je voulais savoir s'il est possible d'avoir un retour d'information.
Par exemple, si je dis "Ok google, uptime", j'aimerais qu'il récupère le résultat de la commande uptime que j'aurais isolé et formaté de manière intelligible (ex: 4 jours) et que GH me dise ainsi "l'uptime est de $" ou $ est "4 jours".
Merci encore

**Comment by Aymkdn** [comment]
Oui c'est possible en utilisant le plugin `notifier` qui fait parler la Google Home.

Ensuite 2 solutions : 
1. soit tu crées [ton propre plugin](https://github.com/Aymkdn/assistant-template) qui va récupérer l'uptime puis le diffuser avec *notifier* (mais il faut savoir programmer JavaScript, mais franchement ce n'est pas compliqué)
2. soit tu ne veux pas programmer en JavaScript, et dans ce cas tu peux utiliser *launch* pour enclencher un programme qui va récupérer l'uptime puis qui va faire une requête vers IFTTT où tu auras créé une applet avec WebHook en entrée, et un Pushbullet Note vers le plugin *notifier* en sortie... Tu peux voir la documentation des WebHook en allant sur [cette page](https://ifttt.com/maker_webhooks) puis en cliquant sur **documentation**

**Comment by nlienard** [comment]
Ok ca m'intéresse. je code en shell et perl mais pas encore JS. tu es sur IRC pour discuter plus simplement ?

**Comment by Aymkdn** [comment]
Je suis sur IRC mais pas forcément plus simple car on peut pas copier de code etc.... et j'y suis beaucoup moins réactif !

**Comment by Aymkdn** [comment]
Je ferme cette issue. N'hésite pas à continuer le fil de discussion si tu as des questions.
