### ISSUE TITLE
Controler son pc avec google home

### ISSUE THREAD

**Issue by FazCodeFR** [Aymkdn/assistant-launch#2]
J'ai codé un script pour controler son ordinateur via google home en passant par assistant-launch

Si ça t’intéresse : 
https://github.com/ABOATDev/Control-Google-Home/ 
https://www.youtube.com/watch?v=Gmt4tIPH_fk

**Comment by Aymkdn** [comment]
Je regarde ça dans une semaine, à mon retour de vacances

**Comment by Aymkdn** [comment]
Je vois que tu as ajouté du VBS pour le décodeur Orange. En fait je souhaite développer un plugin pour ça, mais n'ayant pas de Livebox c'est compliqué.... D'ailleurs tu t'étais proposé pour tester (comme [indiqué ici](https://github.com/Aymkdn/assistant-plugins/issues/21)) mais t'as jamais répondu.

J'ai un pote qui a une Livebox mais j'ai pas encore trouvé le temps d'aller squatter chez lui pour tester.

Concernant ton tuto, quelques remarques : 
  - ton fichier .vbs peut être amélioré, en l'occurrence tu peux regrouper les `Case` qui lance la même commande en les séparant par une virgule ; cela devrait le rendre plus lisible ([voir là](https://www.petri.com/forums/forum/windows-scripting/general-scripting/20821-vbscript-select-case-for-2-of-the-same-options))
  - pourquoi tu dis aux gens d'installer le plugin "IFTTT" ? Ce plugin ne sert QUE pour lancer des WebHooks, et je n'ai pas l'impression que tu as ça dans ton programme... il est donc inutile ici
  - tu devrais supprimer `assistant-plugins.zip` de ton repository car ce n'est pas forcément la dernière version et tu dis de l'effacer ensuite, donc à part créer des confusions, je ne vois pas trop ce qu'il fait là ^^
  - pour vérifier une nouvelle version tu cherches sur Dropbox... pourquoi ne pas le faire sur ton repo Github directement ?
  - à mon avis, il y a moyen de simplifier l'installation en l'intégrant sous le format d'un plugin de `assistant-plugins` ; quand j'ai suffisamment de temps je regarderai ça pour voir comment améliorer la chose

Merci

**Comment by FazCodeFR** [comment]
Je suis partant pour t'aider sur ton plugin décodeur Orange, le plus de mon DecodeurOrange.vbs c'est qu'il fonctionne avec qu'un applet ifttt ce qui est un gros plus pour l'utilisateur. Je me propose testeur que tu choisisse le vbs ou le plugin

- Merci pour l'astuce des `case` je vais l'appliqué pour la prochaine mise a jours

  

- Très bien je vais enlever IFTTT et refaire le tuto ecrit et vidéo

- `assistant-plugins.zip delete` fait

- Dropbox est plus simple (et surtout en français ...) il s'upload automatiquement depuis l'explorateur windows et j'avais remarqué un bug d'affichage Github (caractère spéciaux)  mais je vais arrêter a la prochaine version, seulement Github

- Oui plus simple pour l'utilisateur a mon avis
 



J’arrête de passer par `InternetExplorer.Application` mais par `MSXML2.XMLHTTP` pour la communication ça fais gagner des lignes de codes, et une plus grandes rapidité

**Comment by Aymkdn** [comment]
Le moins de ton DecodeurOrange.vbs c'est qu'il fonctionne avec qu'un applet ifttt justement, et surtout que sous Windows !

Le but est d'offrir de la flexibilité aux gens qui souhaitent personnaliser les commandes, ou ajouter des fonctions supplémentaires. Pour chaque applet on peut définir trois phrases trigger, ce qui offre pas mal de possibilités. Cela laisse aussi le loisir aux gens d'aller au-delà des commandes proposées par défaut (par exemple avec la Freebox certains ont créé des applets pour aller sur leur disque dur externe). Et comme pour la Freebox, je ferai des Applets pré-prêtes donc les gens doivent juste les activer (aucune configuration manuelle à faire). Contrairement à un fichier .vbs qui oblige l'utilisateur à connaitre le code et à mettre les mains dans le cambouis.

Aussi l'avantage d'un plugin est qu'il va fonctionner sur toutes les plateformes où `assistant-plugins` est disponible, et pas seulement sous Windows.

Merci pour ton aide !

**Comment by ABOATDev** [comment]
Très bien je suis d'accord,
Passons par message instantané si tu le veut bien 
Skype: ABOATLeVrai | FB : ABOAT Hack | Discord : ABOAT#5185 ou bien slack.

**Comment by Aymkdn** [comment]
Tu as Hangout ? 😅 Je préférerais si possible

Ou IRC éventuellement (mais je mettrai plus de temps à répondre). 

Sinon je peux me mettre à Slack.

**Comment by ABOATDev** [comment]
Je suis nouveau sur slack aussi 
J'ai créé un "groupe de travail",voici le lien (je sais pas si il fonctionne) 
https://join.slack.com/t/assistant-plugins/shared_invite/enQtMzM3NDA0NDg5NDQ0LTc2NGUzYzk0NWViYzBkMmRkNjgzNGQ2ZGRmYTc1OWIxMWE1Yzk3MGYxYmZhMzIyODYxZjViOTkzNDY0N2MzYjI

**Comment by Aymkdn** [comment]
Voir https://aymkdn.github.io/assistant-plugins/?plugin=control-windows

**Comment by gqueval26** [comment]
bonjour j'ai un problème a le plugins : control-windows peut importe la commande que je mets la commande s’exécute mais j'ai aucune action sur le pc.

**Comment by Aymkdn** [comment]
@gqueval26 peux-tu ouvrir une issue là stp : https://github.com/Aymkdn/assistant-plugins/issues

Ensuite, assure toi de suivre toutes les étapes décrites là : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fréquentes#1-jai-tout-bien-installé-mais-ça-ne-fonctionne-pas

Et enfin, indique dans ton issue ce qu'il en est ainsi que des screenshots.

Ce n'est qu'ainsi que je pourrai t'aider efficacement ! 

Merci
