### ISSUE TITLE
assistant-lanch sur syno

### ISSUE THREAD

**Issue by romain211289** [Aymkdn/assistant-launch#3]
Bonjour,

Tout d'abord merci pour le travail effectué ! L'assistant fonctionne vraiment très bien. D'ailleurs je suis entrain de bosser le js pour enrichir ma Google Home. :D 

Par contre j'aurais une question avant de dl le module lanch et le module control-windows, vu que l'assistant est hébergé sur mon synology, je voulais savoir si tu avait ces modules mais avec  modification d' ip (voir ip statique et création d'une régle NAT/PAT sur mon routeur si il le faut). Si tu n'a pas le module modifié, pense tu que j'ai la possibilité de le modifier pour rajouter la règle moi même et gérer mon pc depuis l'assistant sur syno ? 

Merci

**Comment by Aymkdn** [comment]
Ces deux modules sont pour une exécution locale. `control-windows` est basé sur http://www.nirsoft.net/utils/nircmd.html tandis que `launch` va juste exécuter un fichier qui est en local.

Si je comprends ta question, tu veux savoir si tu peux utiliser ces modules pour piloter ton PC à distance depuis ton Syno ? À priori non, tu ne peux pas. Même si [nircmd propose une fonction "remote"](https://nircmd.nirsoft.net/remote.html), il faudrait que `assistant-plugins` tourne sous Windows déjà...

**Comment by romain211289** [comment]
Ah ok, oui s'est exactement ça ;).  J'avais vu que ces modules tournaient en local avec assistant sur windows, du coup je me demandais si il n'y avait pas une autre solution.. (j'ai m'a réponse.) 
Merci!
